apiVersion: v1
kind: Secret
metadata:
  name: musiclab-secret
  namespace: musiclab
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "musiclab"
  RABBITMQ_DEFAULT_PASS: "musiclab_pw"
  # Stessa URL AMQP usata in .env, ma con host = nome del Service k8s "rabbitmq"
  RABBITMQ_URL: "amqp://musiclab:musiclab_pw@rabbitmq:5672"
